version: "3.9"

services:
  # app:
  #   build: .
  #   container_name: crud_app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb"
  #     REDIS_URL: "redis://redis:6379"
  #     JWT_SECRET: "secret"
  #   depends_on:
  #     - db
  #     - redis
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: mydb
      PGDATA: /data/postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: