version: "3.9"

services:
  app:
    build: ./crud_app
    container_name: crud_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: 'redis://redis:6379'
      JWT_SECRET: 'secret'
      NODE_ENV: 'development'
      DATABASE_HOST: 'db'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgrespass'
      DATABASE_PORT: '5432'
      DATABASE_NAME: 'mydb'
    depends_on:
      - db
      - redis
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: mydb
      PGDATA: /data/postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: